"""Make product_id in OrderItem nullable and add ON DELETE SET NULL

Revision ID: d8cba9826da7
Revises: 232355ed158e
Create Date: 2025-06-20 12:24:00.047486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8cba9826da7'
down_revision: Union[str, None] = '232355ed158e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('orderitem', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('orderitem_product_id_fkey'), 'orderitem', type_='foreignkey')
    op.create_foreign_key(None, 'orderitem', 'product', ['product_id'], ['id'], ondelete='SET NULL')
    op.alter_column('product', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.create_foreign_key(op.f('orderitem_product_id_fkey'), 'orderitem', 'product', ['product_id'], ['id'])
    op.alter_column('orderitem', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('cart', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
